# Generated by Django 4.0.4 on 2022-04-13 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='phone_number'),
        ),
    ]
