# Generated by Django 4.0.3 on 2022-04-10 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0002_creditor_wallet_wallettransaction_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AlterField(
            model_name='creditor',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 15, 8, 37, 753850, tzinfo=utc), verbose_name='date_due'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=40, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=250, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('credit', 'Credit')], max_length=100, verbose_name='transaction_type'),
        ),
    ]
