# Generated by Django 4.0.4 on 2022-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
    ]
