# Generated by Django 4.0.4 on 2022-04-12 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0003_alter_creditor_date_due_alter_creditor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 13, 45, 36, 923825, tzinfo=utc), verbose_name='date_due'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='name'),
        ),
    ]
