# Generated by Django 4.0.3 on 2022-04-11 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0003_remove_wallet_balance_alter_creditor_date_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='destination',
        ),
        migrations.AlterField(
            model_name='creditor',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 12, 17, 54, 552704, tzinfo=utc), verbose_name='date_due'),
        ),
    ]
