# Generated by Django 4.0.4 on 2022-04-13 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0004_alter_creditor_date_due_alter_creditor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='date_due',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_due'),
        ),
    ]
