# Generated by Django 4.0.3 on 2022-04-11 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0004_remove_wallettransaction_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='paystack_reference',
            field=models.CharField(max_length=100, null=True, verbose_name='paystack_reference'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 15, 8, 59, 45289, tzinfo=utc), verbose_name='date_due'),
        ),
    ]
